import Country from "./Country";

const countries: Array<Country> = [
  {
    name: "Afghanistan",
    capital: "Kabul",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Afghanistan.svg",
    iso2: "AF",
    iso3: "AFG",
    dail_code: "+93",
    latitude: 33,
    longitude: 65,
    currency: {
      unicode: "🇦🇫",
      code: "AFA",
      name: "Afghan Afghani",
      symbol: "؋",
    },
  },
  {
    name: "Albania",
    capital: "Tirana",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg",
    iso2: "AL",
    iso3: "ALB",
    dail_code: "+355",
    latitude: 41,
    longitude: 20,
    currency: {
      unicode: "🇦🇱",
      code: "ALL",
      name: "Albanian Lek",
      symbol: "Lek",
    },
  },
  {
    name: "Algeria",
    capital: "Algiers",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg",
    iso2: "DZ",
    iso3: "DZA",
    dail_code: "+213",
    latitude: 28,
    longitude: 3,
    currency: {
      unicode: "🇩🇿",
      code: "DZD",
      name: "Algerian Dinar",
      symbol: "دج",
    },
  },
  {
    name: "Andorra",
    capital: "Andorra la Vella",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Andorra.svg",
    iso2: "AD",
    iso3: "AND",
    dail_code: "+376",
    latitude: 42.5,
    longitude: 1.6,
    currency: {
      unicode: "🇦🇩",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Angola",
    capital: "Luanda",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg",
    iso2: "AO",
    iso3: "AGO",
    dail_code: "+244",
    latitude: -12.5,
    longitude: 18.5,
    currency: {
      unicode: "🇦🇴",
      code: "AOA",
      name: "Angolan Kwanza",
      symbol: "Kz",
    },
  },
  {
    name: "Anguilla",
    capital: "The Valley",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Anguilla.svg",
    iso2: "AI",
    iso3: "AIA",
    dail_code: "+1264",
    latitude: 18.25,
    longitude: -63.1667,
    currency: {
      unicode: "🇦🇮",
      code: "XCD",
      name: "East Caribbean Dollar",
      symbol: "$",
    },
  },
  {
    name: "Antigua and Barbuda",
    capital: "St. John's",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg",
    iso2: "AG",
    iso3: "ATG",
    dail_code: "+1268",
    latitude: 17.05,
    longitude: -61.8,
    currency: {
      unicode: "🇦🇬",
      code: "XCD",
      name: "East Caribbean Dollar",
      symbol: "$",
    },
  },
  {
    name: "Argentina",
    capital: "Buenos Aires",
    continent: "SA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
    iso2: "AR",
    iso3: "ARG",
    dail_code: "+54",
    latitude: -34,
    longitude: -64,
    currency: {
      unicode: "🇦🇷",
      code: "ARS",
      name: "Argentine Peso",
      symbol: "$",
    },
  },
  {
    name: "Armenia",
    capital: "Yerevan",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg",
    iso2: "AM",
    iso3: "ARM",
    dail_code: "+374",
    latitude: 40,
    longitude: 45,
    currency: {
      unicode: "🇦🇲",
      code: "AMD",
      name: "Armenian Dram",
      symbol: "֏",
    },
  },
  {
    name: "Aruba",
    capital: "Oranjestad",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Aruba.svg",
    iso2: "AW",
    iso3: "ABW",
    dail_code: "+297",
    latitude: 12.5,
    longitude: -69.9667,
    currency: {
      unicode: "🇦🇼",
      code: "AWG",
      name: "Aruban Florin",
      symbol: "ƒ",
    },
  },
  {
    name: "Australia",
    capital: "Canberra",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia_%28converted%29.svg",
    iso2: "AU",
    iso3: "AUS",
    dail_code: "+61",
    latitude: -27,
    longitude: 133,
    currency: {
      unicode: "🇦🇺",
      code: "AUD",
      name: "Australian Dollar",
      symbol: "$",
    },
  },
  {
    name: "Austria",
    capital: "Vienna",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg",
    iso2: "AT",
    iso3: "AUT",
    dail_code: "+43",
    latitude: 47.3333,
    longitude: 13.3333,
    currency: {
      unicode: "🇦🇹",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Azerbaijan",
    capital: "Baku",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg",
    iso2: "AZ",
    iso3: "AZE",
    dail_code: "+994",
    latitude: 40.5,
    longitude: 47.5,
    currency: {
      unicode: "🇦🇿",
      code: "AZN",
      name: "Azerbaijani Manat",
      symbol: "m",
    },
  },
  {
    name: "Bahamas",
    capital: "Nassau",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg",
    iso2: "BS",
    iso3: "BHS",
    dail_code: "+1242",
    latitude: 24.25,
    longitude: -76,
    currency: {
      unicode: "🇧🇸",
      code: "BSD",
      name: "Bahamian Dollar",
      symbol: "B$",
    },
  },
  {
    name: "Bahrain",
    capital: "Manama",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg",
    iso2: "BH",
    iso3: "BHR",
    dail_code: "+973",
    latitude: 26,
    longitude: 50.55,
    currency: {
      unicode: "🇧🇭",
      code: "BHD",
      name: "Bahraini Dinar",
      symbol: ".د.ب",
    },
  },
  {
    name: "Bangladesh",
    capital: "Dhaka",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg",
    iso2: "BD",
    iso3: "BGD",
    dail_code: "+880",
    latitude: 24,
    longitude: 90,
    currency: {
      unicode: "🇧🇩",
      code: "BDT",
      name: "Bangladeshi Taka",
      symbol: "৳",
    },
  },
  {
    name: "Barbados",
    capital: "Bridgetown",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg",
    iso2: "BB",
    iso3: "BRB",
    dail_code: "+1246",
    latitude: 13.1667,
    longitude: -59.5333,
    currency: {
      unicode: "🇧🇧",
      code: "BBD",
      name: "Barbadian Dollar",
      symbol: "Bds$",
    },
  },
  {
    name: "Belarus",
    capital: "Minsk",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg",
    iso2: "BY",
    iso3: "BLR",
    dail_code: "+375",
    latitude: 53,
    longitude: 28,
    currency: {
      unicode: "🇧🇾",
      code: "BYR",
      name: "Belarusian Ruble",
      symbol: "Br",
    },
  },
  {
    name: "Belgium",
    capital: "Brussels",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg",
    iso2: "BE",
    iso3: "BEL",
    dail_code: "+32",
    latitude: 50.8333,
    longitude: 4,
    currency: {
      unicode: "🇧🇪",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Belize",
    capital: "Belmopan",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg",
    iso2: "BZ",
    iso3: "BLZ",
    dail_code: "+501",
    latitude: 17.25,
    longitude: -88.75,
    currency: {
      unicode: "🇧🇿",
      code: "BZD",
      name: "Belize Dollar",
      symbol: "$",
    },
  },
  {
    name: "Benin",
    capital: "Porto-Novo",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg",
    iso2: "BJ",
    iso3: "BEN",
    dail_code: "+229",
    latitude: 9.5,
    longitude: 2.25,
    currency: {
      unicode: "🇧🇯",
      code: "XOF",
      name: "CFA Franc BCEAO",
      symbol: "CFA",
    },
  },
  {
    name: "Bermuda",
    capital: "Hamilton",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bermuda.svg",
    iso2: "BM",
    iso3: "BMU",
    dail_code: "+1441",
    latitude: 32.3333,
    longitude: -64.75,
    currency: {
      unicode: "🇧🇲",
      code: "BMD",
      name: "Bermudan Dollar",
      symbol: "$",
    },
  },
  {
    name: "Bhutan",
    capital: "Thimphu",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg",
    iso2: "BT",
    iso3: "BTN",
    dail_code: "+975",
    latitude: 27.5,
    longitude: 90.5,
    currency: {
      unicode: "🇧🇹",
      code: "BTN",
      name: "Bhutanese Ngultrum",
      symbol: "Nu.",
    },
  },
  {
    name: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg",
    iso2: "BA",
    iso3: "BIH",
    dail_code: "+387",
    latitude: 44,
    longitude: 18,
    currency: {
      unicode: "🇧🇦",
      code: "BAM",
      name: "Bosnia-Herzegovina Convertible Mark",
      symbol: "KM",
    },
  },
  {
    name: "Botswana",
    capital: "Gaborone",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg",
    iso2: "BW",
    iso3: "BWA",
    dail_code: "+267",
    latitude: -22,
    longitude: 24,
    currency: {
      unicode: "🇧🇼",
      code: "BWP",
      name: "Botswanan Pula",
      symbol: "P",
    },
  },
  {
    name: "Bouvet Island",
    capital: "",
    continent: "AN",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg",
    iso2: "BV",
    iso3: "BVT",
    dail_code: "+55",
    latitude: -54.4333,
    longitude: 3.4,
    currency: {
      unicode: "🇧🇻",
      code: "NOK",
      name: "Norwegian Krone",
      symbol: "kr",
    },
  },
  {
    name: "Brazil",
    capital: "Brasilia",
    continent: "SA",
    flag: "https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg",
    iso2: "BR",
    iso3: "BRA",
    dail_code: "+55",
    latitude: -10,
    longitude: -55,
    currency: {
      unicode: "🇧🇷",
      code: "BRL",
      name: "Brazilian Real",
      symbol: "R$",
    },
  },
  {
    name: "British Indian Ocean Territory",
    capital: "Diego Garcia",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_the_British_Indian_Ocean_Territory.svg",
    iso2: "IO",
    iso3: "IOT",
    dail_code: "+246",
    latitude: -6,
    longitude: 71.5,
    currency: {
      unicode: "🇮🇴",
      code: "USD",
      name: "US Dollar",
      symbol: "$",
    },
  },
  {
    name: "Brunei Darussalam",
    capital: "Bandar Seri Begawan",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg",
    iso2: "BN",
    iso3: "BRN",
    dail_code: "+673",
    latitude: 4.5,
    longitude: 114.6667,
    currency: {
      unicode: "🇧🇳",
      code: "BND",
      name: "Brunei Dollar",
      symbol: "B$",
    },
  },
  {
    name: "Bulgaria",
    capital: "Sofia",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg",
    iso2: "BG",
    iso3: "BGR",
    dail_code: "+359",
    latitude: 43,
    longitude: 25,
    currency: {
      unicode: "🇧🇬",
      code: "BGN",
      name: "Bulgarian Lev",
      symbol: "Лв.",
    },
  },
  {
    name: "Burkina Faso",
    capital: "Ouagadougou",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg",
    iso2: "BF",
    iso3: "BFA",
    dail_code: "+226",
    latitude: 13,
    longitude: -2,
    currency: {
      unicode: "🇧🇫",
      code: "XOF",
      name: "CFA Franc BCEAO",
      symbol: "CFA",
    },
  },
  {
    name: "Burundi",
    capital: "Bujumbura",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Burundi.svg",
    iso2: "BI",
    iso3: "BDI",
    dail_code: "+257",
    latitude: -3.5,
    longitude: 30,
    currency: {
      unicode: "🇧🇮",
      code: "BIF",
      name: "Burundian Franc",
      symbol: "FBu",
    },
  },
  {
    name: "Cambodia",
    capital: "Phnom Penh",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg",
    iso2: "KH",
    iso3: "KHM",
    dail_code: "+855",
    latitude: 13,
    longitude: 105,
    currency: {
      unicode: "🇰🇭",
      code: "KHR",
      name: "Cambodian Riel",
      symbol: "KHR",
    },
  },
  {
    name: "Cameroon",
    capital: "Yaounde",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg",
    iso2: "CM",
    iso3: "CMR",
    dail_code: "+237",
    latitude: 6,
    longitude: 12,
    currency: {
      unicode: "🇨🇲",
      code: "XAF",
      name: "CFA Franc BEAC",
      symbol: "FCFA",
    },
  },
  {
    name: "Canada",
    capital: "Ottawa",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/en/c/cf/Flag_of_Canada.svg",
    iso2: "CA",
    iso3: "CAN",
    dail_code: "+1",
    latitude: 60,
    longitude: -95,
    currency: {
      unicode: "🇨🇦",
      code: "CAD",
      name: "Canadian Dollar",
      symbol: "$",
    },
  },
  {
    name: "Cape Verde",
    capital: "Praia",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg",
    iso2: "CV",
    iso3: "CPV",
    dail_code: "+238",
    latitude: 16,
    longitude: -24,
    currency: {
      unicode: "🇨🇻",
      code: "CVE",
      name: "Cape Verdean Escudo",
      symbol: "$",
    },
  },
  {
    name: "Cayman Islands",
    capital: "George Town",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_the_Cayman_Islands.svg",
    iso2: "KY",
    iso3: "CYM",
    dail_code: "+1345",
    latitude: 19.5,
    longitude: -80.5,
    currency: {
      unicode: "🇰🇾",
      code: "KYD",
      name: "Cayman Islands Dollar",
      symbol: "$",
    },
  },
  {
    name: "Central African Republic",
    capital: "Bangui",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Central_African_Republic.svg",
    iso2: "CF",
    iso3: "CAF",
    dail_code: "+236",
    latitude: 7,
    longitude: 21,
    currency: {
      unicode: "🇨🇫",
      code: "XAF",
      name: "CFA Franc BEAC",
      symbol: "FCFA",
    },
  },
  {
    name: "Chad",
    capital: "N'Djamena",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg",
    iso2: "TD",
    iso3: "TCD",
    dail_code: "+235",
    latitude: 15,
    longitude: 19,
    currency: {
      unicode: "🇹🇩",
      code: "XAF",
      name: "CFA Franc BEAC",
      symbol: "FCFA",
    },
  },
  {
    name: "Chile",
    capital: "Santiago",
    continent: "SA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg",
    iso2: "CL",
    iso3: "CHL",
    dail_code: "+56",
    latitude: -30,
    longitude: -71,
    currency: {
      unicode: "🇨🇱",
      code: "CLP",
      name: "Chilean Peso",
      symbol: "$",
    },
  },
  {
    name: "China",
    capital: "Beijing",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg",
    iso2: "CN",
    iso3: "CHN",
    dail_code: "+86",
    latitude: 35,
    longitude: 105,
    currency: {
      unicode: "🇨🇳",
      code: "CNY",
      name: "Chinese Yuan",
      symbol: "¥",
    },
  },
  {
    name: "Christmas Island",
    capital: "Flying Fish Cove",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/67/Flag_of_Christmas_Island.svg",
    iso2: "CX",
    iso3: "CXR",
    dail_code: "+61",
    latitude: -10.5,
    longitude: 105.6667,
    currency: {
      unicode: "🇨🇽",
      code: "AUD",
      name: "Australian Dollar",
      symbol: "$",
    },
  },
  {
    name: "Cocos Islands",
    capital: "West Island",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Cocos_%28Keeling%29_Islands.svg",
    iso2: "CC",
    iso3: "CCK",
    dail_code: "+61",
    latitude: -12.5,
    longitude: 96.8333,
    currency: {
      unicode: "🇨🇨",
      code: "AUD",
      name: "Australian Dollar",
      symbol: "$",
    },
  },
  {
    name: "Colombia",
    capital: "Bogota",
    continent: "SA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg",
    iso2: "CO",
    iso3: "COL",
    dail_code: "+57",
    latitude: 4,
    longitude: -72,
    currency: {
      unicode: "🇨🇴",
      code: "COP",
      name: "Colombian Peso",
      symbol: "$",
    },
  },
  {
    name: "Comoros",
    capital: "Moroni",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg",
    iso2: "KM",
    iso3: "COM",
    dail_code: "+269",
    latitude: -12.1667,
    longitude: 44.25,
    currency: {
      unicode: "🇰🇲",
      code: "KMF",
      name: "Comorian Franc",
      symbol: "CF",
    },
  },
  {
    name: "Congo",
    capital: "Brazzaville",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_the_Republic_of_the_Congo.svg",
    iso2: "CG",
    iso3: "COG",
    dail_code: "+242",
    latitude: -1,
    longitude: 15,
    currency: {
      unicode: "🇨🇬",
      code: "XAF",
      name: "CFA Franc BEAC",
      symbol: "FCFA",
    },
  },
  {
    name: "Cook Islands",
    capital: "Avarua",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_the_Cook_Islands.svg",
    iso2: "CK",
    iso3: "COK",
    dail_code: "+682",
    latitude: -21.2333,
    longitude: -159.7667,
    currency: {
      unicode: "🇨🇰",
      code: "NZD",
      name: "New Zealand Dollar",
      symbol: "$",
    },
  },
  {
    name: "Costa Rica",
    capital: "San Jose",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Costa_Rica_%28state%29.svg",
    iso2: "CR",
    iso3: "CRI",
    dail_code: "+506",
    latitude: 10,
    longitude: -84,
    currency: {
      unicode: "🇨🇷",
      code: "CRC",
      name: "Costa Rican ColÃ³n",
      symbol: "₡",
    },
  },
  {
    name: "Croatia",
    capital: "Zagreb",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg",
    iso2: "HR",
    iso3: "HRV",
    dail_code: "+385",
    latitude: 45.1667,
    longitude: 15.5,
    currency: {
      unicode: "🇭🇷",
      code: "HRK",
      name: "Croatian Kuna",
      symbol: "kn",
    },
  },
  {
    name: "Cuba",
    capital: "Havana",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg",
    iso2: "CU",
    iso3: "CUB",
    dail_code: "+53",
    latitude: 21.5,
    longitude: -80,
    currency: {
      unicode: "🇨🇺",
      code: "CUP",
      name: "Cuban Peso",
      symbol: "₱",
    },
  },
  {
    name: "Cyprus",
    capital: "Nicosia",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg",
    iso2: "CY",
    iso3: "CYP",
    dail_code: "+357",
    latitude: 35,
    longitude: 33,
    currency: {
      unicode: "🇨🇾",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Czech Republic",
    capital: "Prague",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg",
    iso2: "CZ",
    iso3: "CZE",
    dail_code: "+420",
    latitude: 49.75,
    longitude: 15.5,
    currency: {
      unicode: "🇨🇿",
      code: "CZK",
      name: "Czech Republic Koruna",
      symbol: "Kč",
    },
  },
  {
    name: "Denmark",
    capital: "Copenhagen",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg",
    iso2: "DK",
    iso3: "DNK",
    dail_code: "+45",
    latitude: 56,
    longitude: 10,
    currency: {
      unicode: "🇩🇰",
      code: "DKK",
      name: "Danish Krone",
      symbol: "Kr.",
    },
  },
  {
    name: "Djibouti",
    capital: "Djibouti",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg",
    iso2: "DJ",
    iso3: "DJI",
    dail_code: "+253",
    latitude: 11.5,
    longitude: 43,
    currency: {
      unicode: "🇩🇯",
      code: "DJF",
      name: "Djiboutian Franc",
      symbol: "Fdj",
    },
  },
  {
    name: "Dominica",
    capital: "Roseau",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg",
    iso2: "DM",
    iso3: "DMA",
    dail_code: "+1767",
    latitude: 15.4167,
    longitude: -61.3333,
    currency: {
      unicode: "🇩🇲",
      code: "XCD",
      name: "East Caribbean Dollar",
      symbol: "$",
    },
  },
  {
    name: "Dominican Republic",
    capital: "Santo Domingo",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg",
    iso2: "DO",
    iso3: "DOM",
    dail_code: "+1849",
    latitude: 19,
    longitude: -70.6667,
    currency: {
      unicode: "🇩🇴",
      code: "DOP",
      name: "Dominican Peso",
      symbol: "$",
    },
  },
  {
    name: "East Timor",
    capital: "Dili",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/26/Flag_of_East_Timor.svg",
    iso2: "TL",
    iso3: "TLS",
    dail_code: "+670",
    latitude: -8.55,
    longitude: 125.5167,
    currency: {
      unicode: "🇹🇱",
      code: "USD",
      name: "US Dollar",
      symbol: "$",
    },
  },
  {
    name: "Ecuador",
    capital: "Quito",
    continent: "SA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg",
    iso2: "EC",
    iso3: "ECU",
    dail_code: "+593",
    latitude: -2,
    longitude: -77.5,
    currency: {
      unicode: "🇪🇨",
      code: "USD",
      name: "US Dollar",
      symbol: "$",
    },
  },
  {
    name: "Egypt",
    capital: "Cairo",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg",
    iso2: "EG",
    iso3: "EGY",
    dail_code: "+20",
    latitude: 27,
    longitude: 30,
    currency: {
      unicode: "🇪🇬",
      code: "EGP",
      name: "Egyptian Pound",
      symbol: "ج.م",
    },
  },
  {
    name: "El Salvador",
    capital: "San Salvador",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg",
    iso2: "SV",
    iso3: "SLV",
    dail_code: "+503",
    latitude: 13.8333,
    longitude: -88.9167,
    currency: {
      unicode: "🇸🇻",
      code: "USD",
      name: "US Dollar",
      symbol: "$",
    },
  },
  {
    name: "Equatorial Guinea",
    capital: "Malabo",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg",
    iso2: "GQ",
    iso3: "GNQ",
    dail_code: "+240",
    latitude: 2,
    longitude: 10,
    currency: {
      unicode: "🇬🇶",
      code: "XAF",
      name: "CFA Franc BEAC",
      symbol: "FCFA",
    },
  },
  {
    name: "Eritrea",
    capital: "Asmara",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg",
    iso2: "ER",
    iso3: "ERI",
    dail_code: "+291",
    latitude: 15,
    longitude: 39,
    currency: {
      unicode: "🇪🇷",
      code: "ERN",
      name: "Eritrean Nakfa",
      symbol: "Nfk",
    },
  },
  {
    name: "Estonia",
    capital: "Tallinn",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg",
    iso2: "EE",
    iso3: "EST",
    dail_code: "+372",
    latitude: 59,
    longitude: 26,
    currency: {
      unicode: "🇪🇪",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Eswatini",
    capital: "Mbabane",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Swaziland_1894.svg",
    iso2: "SZ",
    iso3: "SWZ",
    dail_code: "+268",
    latitude: -26.5,
    longitude: 31.5,
    currency: {
      unicode: "🇸🇿",
      code: "SZL",
      name: "Swazi Lilangeni",
      symbol: "E",
    },
  },
  {
    name: "Ethiopia",
    capital: "Addis Ababa",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg",
    iso2: "ET",
    iso3: "ETH",
    dail_code: "+251",
    latitude: 8,
    longitude: 38,
    currency: {
      unicode: "🇪🇹",
      code: "ETB",
      name: "Ethiopian Birr",
      symbol: "Nkf",
    },
  },
  {
    name: "Falkland Islands",
    capital: "Stanley",
    continent: "SA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_Falkland_Islands.svg",
    iso2: "FK",
    iso3: "FLK",
    dail_code: "+500",
    latitude: -51.75,
    longitude: -59,
    currency: {
      unicode: "🇫🇰",
      code: "FKP",
      name: "Falkland Islands Pound",
      symbol: "£",
    },
  },
  {
    name: "Faroe Islands",
    capital: "Torshavn",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Flag_of_the_Faroe_Islands.svg",
    iso2: "FO",
    iso3: "FRO",
    dail_code: "+298",
    latitude: 62,
    longitude: -7,
    currency: {
      unicode: "🇫🇴",
      code: "DKK",
      name: "Danish Krone",
      symbol: "Kr.",
    },
  },
  {
    name: "Fiji",
    capital: "Suva",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg",
    iso2: "FJ",
    iso3: "FJI",
    dail_code: "+679",
    latitude: -18,
    longitude: 175,
    currency: {
      unicode: "🇫🇯",
      code: "FJD",
      name: "Fijian Dollar",
      symbol: "FJ$",
    },
  },
  {
    name: "Finland",
    capital: "Helsinki",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg",
    iso2: "FI",
    iso3: "FIN",
    dail_code: "+358",
    latitude: 64,
    longitude: 26,
    currency: {
      unicode: "🇫🇮",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "France",
    capital: "Paris",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg",
    iso2: "FR",
    iso3: "FRA",
    dail_code: "+33",
    latitude: 46,
    longitude: 2,
    currency: {
      unicode: "🇫🇷",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "French Guiana",
    capital: "Cayenne",
    continent: "SA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_French_Guiana.svg",
    iso2: "GF",
    iso3: "GUF",
    dail_code: "+594",
    latitude: 4,
    longitude: -53,
    currency: {
      unicode: "🇬🇫",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "French Polynesia",
    capital: "Papeete",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/db/Flag_of_French_Polynesia.svg",
    iso2: "PF",
    iso3: "PYF",
    dail_code: "+689",
    latitude: -15,
    longitude: -140,
    currency: {
      unicode: "🇵🇫",
      code: "XPF",
      name: "CFP Franc",
      symbol: "₣",
    },
  },
  {
    name: "Gabon",
    capital: "Libreville",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg",
    iso2: "GA",
    iso3: "GAB",
    dail_code: "+241",
    latitude: -1,
    longitude: 11.75,
    currency: {
      unicode: "🇬🇦",
      code: "XAF",
      name: "CFA Franc BEAC",
      symbol: "FCFA",
    },
  },
  {
    name: "Gambia",
    capital: "Banjul",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg",
    iso2: "GM",
    iso3: "GMB",
    dail_code: "+220",
    latitude: 13.4667,
    longitude: -16.5667,
    currency: {
      unicode: "🇬🇲",
      code: "GMD",
      name: "Gambian Dalasi",
      symbol: "D",
    },
  },
  {
    name: "Georgia",
    capital: "Tbilisi",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg",
    iso2: "GE",
    iso3: "GEO",
    dail_code: "+995",
    latitude: 42,
    longitude: 43.5,
    currency: {
      unicode: "🇬🇪",
      code: "GEL",
      name: "Georgian Lari",
      symbol: "ლ",
    },
  },
  {
    name: "Germany",
    capital: "Berlin",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg",
    iso2: "DE",
    iso3: "DEU",
    dail_code: "+49",
    latitude: 51,
    longitude: 9,
    currency: {
      unicode: "🇩🇪",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Ghana",
    capital: "Accra",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg",
    iso2: "GH",
    iso3: "GHA",
    dail_code: "+233",
    latitude: 8,
    longitude: -2,
    currency: {
      unicode: "🇬🇭",
      code: "GHS",
      name: "Ghanaian Cedi",
      symbol: "GH₵",
    },
  },
  {
    name: "Gibraltar",
    capital: "Gibraltar",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/02/Flag_of_Gibraltar.svg",
    iso2: "GI",
    iso3: "GIB",
    dail_code: "+350",
    latitude: 36.1833,
    longitude: -5.3667,
    currency: {
      unicode: "🇬🇮",
      code: "GIP",
      name: "Gibraltar Pound",
      symbol: "£",
    },
  },
  {
    name: "Greece",
    capital: "Athens",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg",
    iso2: "GR",
    iso3: "GRC",
    dail_code: "+30",
    latitude: 39,
    longitude: 22,
    currency: {
      unicode: "🇬🇷",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Greenland",
    capital: "Nuuk",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_Greenland.svg",
    iso2: "GL",
    iso3: "GRL",
    dail_code: "+299",
    latitude: 72,
    longitude: -40,
    currency: {
      unicode: "🇬🇱",
      code: "DKK",
      name: "Danish Krone",
      symbol: "Kr.",
    },
  },
  {
    name: "Grenada",
    capital: "St. George's",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg",
    iso2: "GD",
    iso3: "GRD",
    dail_code: "+1473",
    latitude: 12.1167,
    longitude: -61.6667,
    currency: {
      unicode: "🇬🇩",
      code: "XCD",
      name: "East Caribbean Dollar",
      symbol: "$",
    },
  },
  {
    name: "Guadeloupe",
    capital: "Basse-Terre",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Unofficial_flag_of_Guadeloupe_%28local%29.svg",
    iso2: "GP",
    iso3: "GLP",
    dail_code: "+590",
    latitude: 16.25,
    longitude: -61.5833,
    currency: {
      unicode: "🇬🇵",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Guam",
    capital: "Hagatna",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/07/Flag_of_Guam.svg",
    iso2: "GU",
    iso3: "GUM",
    dail_code: "+1671",
    latitude: 13.4667,
    longitude: 144.7833,
    currency: {
      unicode: "🇬🇺",
      code: "USD",
      name: "US Dollar",
      symbol: "$",
    },
  },
  {
    name: "Guatemala",
    capital: "Guatemala City",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg",
    iso2: "GT",
    iso3: "GTM",
    dail_code: "+502",
    latitude: 15.5,
    longitude: -90.25,
    currency: {
      unicode: "🇬🇹",
      code: "GTQ",
      name: "Guatemalan Quetzal",
      symbol: "Q",
    },
  },
  {
    name: "Guernsey",
    capital: "St Peter Port",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Guernsey.svg",
    iso2: "GG",
    iso3: "GGY",
    dail_code: "+44",
    latitude: 49.5,
    longitude: -2.56,
    currency: {
      unicode: "🇬🇬",
      code: "GBP",
      name: "British Pound Sterling",
      symbol: "£",
    },
  },
  {
    name: "Guinea",
    capital: "Conakry",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg",
    iso2: "GN",
    iso3: "GIN",
    dail_code: "+224",
    latitude: 11,
    longitude: -10,
    currency: {
      unicode: "🇬🇳",
      code: "GNF",
      name: "Guinean Franc",
      symbol: "FG",
    },
  },
  {
    name: "Guinea-Bissau",
    capital: "Bissau",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg",
    iso2: "GW",
    iso3: "GNB",
    dail_code: "+245",
    latitude: 12,
    longitude: -15,
    currency: {
      unicode: "🇬🇼",
      code: "XOF",
      name: "CFA Franc BCEAO",
      symbol: "CFA",
    },
  },
  {
    name: "Guyana",
    capital: "Georgetown",
    continent: "SA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg",
    iso2: "GY",
    iso3: "GUY",
    dail_code: "+592",
    latitude: 5,
    longitude: -59,
    currency: {
      unicode: "🇬🇾",
      code: "GYD",
      name: "Guyanaese Dollar",
      symbol: "$",
    },
  },
  {
    name: "Haiti",
    capital: "Port-au-Prince",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg",
    iso2: "HT",
    iso3: "HTI",
    dail_code: "+509",
    latitude: 19,
    longitude: -72.4167,
    currency: {
      unicode: "🇭🇹",
      code: "HTG",
      name: "Haitian Gourde",
      symbol: "G",
    },
  },
  {
    name: "Heard Island and McDonald Islands",
    capital: "",
    continent: "AN",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg",
    iso2: "HM",
    iso3: "HMD",
    dail_code: "+672",
    latitude: -53.1,
    longitude: 72.5167,
    currency: {
      unicode: "🇭🇲",
      code: "AUD",
      name: "Australian Dollar",
      symbol: "$",
    },
  },
  {
    name: "Honduras",
    capital: "Tegucigalpa",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Naval_Ensign_of_Honduras.svg",
    iso2: "HN",
    iso3: "HND",
    dail_code: "+504",
    latitude: 15,
    longitude: -86.5,
    currency: {
      unicode: "🇭🇳",
      code: "HNL",
      name: "Honduran Lempira",
      symbol: "L",
    },
  },
  {
    name: "Hong Kong",
    capital: "Hong Kong",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Hong_Kong.svg",
    iso2: "HK",
    iso3: "HKG",
    dail_code: "+852",
    latitude: 22.25,
    longitude: 114.1667,
    currency: {
      unicode: "🇭🇰",
      code: "HKD",
      name: "Hong Kong Dollar",
      symbol: "$",
    },
  },
  {
    name: "Hungary",
    capital: "Budapest",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg",
    iso2: "HU",
    iso3: "HUN",
    dail_code: "+36",
    latitude: 47,
    longitude: 20,
    currency: {
      unicode: "🇭🇺",
      code: "HUF",
      name: "Hungarian Forint",
      symbol: "Ft",
    },
  },
  {
    name: "Iceland",
    capital: "Reykjavik",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg",
    iso2: "IS",
    iso3: "ISL",
    dail_code: "+354",
    latitude: 65,
    longitude: -18,
    currency: {
      unicode: "🇮🇸",
      code: "ISK",
      name: "Icelandic KrÃ³na",
      symbol: "kr",
    },
  },
  {
    name: "India",
    capital: "New Delhi",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg",
    iso2: "IN",
    iso3: "IND",
    dail_code: "+91",
    latitude: 20,
    longitude: 77,
    currency: {
      unicode: "🇮🇳",
      code: "INR",
      name: "Indian Rupee",
      symbol: "₹",
    },
  },
  {
    name: "Indonesia",
    capital: "Jakarta",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg",
    iso2: "ID",
    iso3: "IDN",
    dail_code: "+62",
    latitude: -5,
    longitude: 120,
    currency: {
      unicode: "🇮🇩",
      code: "IDR",
      name: "Indonesian Rupiah",
      symbol: "Rp",
    },
  },
  {
    name: "Iran",
    capital: "Tehran",
    continent: "AS",
    flag: " https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg",
    iso2: "IR",
    iso3: "IRN",
    dail_code: "+98",
    latitude: 32,
    longitude: 53,
    currency: {
      unicode: "🇮🇷",
      code: "IRR",
      name: "Iranian Rial",
      symbol: "﷼",
    },
  },
  {
    name: "Iraq",
    capital: "Baghdad",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg",
    iso2: "IQ",
    iso3: "IRQ",
    dail_code: "+964",
    latitude: 33,
    longitude: 44,
    currency: {
      unicode: "🇮🇶",
      code: "IQD",
      name: "Iraqi Dinar",
      symbol: "د.ع",
    },
  },
  {
    name: "Ireland",
    capital: "Dublin",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg",
    iso2: "IE",
    iso3: "IRL",
    dail_code: "+353",
    latitude: 53,
    longitude: -8,
    currency: {
      unicode: "🇮🇪",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Isle of Man",
    capital: "Douglas, Isle of Man",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_the_Isle_of_Man.svg",
    iso2: "IM",
    iso3: "IMN",
    dail_code: "+44",
    latitude: 54.23,
    longitude: -4.55,
    currency: {
      unicode: "🇮🇲",
      code: "GBP",
      name: "British Pound Sterling",
      symbol: "£",
    },
  },
  {
    name: "Israel",
    capital: "Jerusalem",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg",
    iso2: "IL",
    iso3: "ISR",
    dail_code: "+972",
    latitude: 31.5,
    longitude: 34.75,
    currency: {
      unicode: "🇮🇱",
      code: "ILS",
      name: "Israeli New Sheqel",
      symbol: "₪",
    },
  },
  {
    name: "Italy",
    capital: "Rome",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg",
    iso2: "IT",
    iso3: "ITA",
    dail_code: "+39",
    latitude: 42.8333,
    longitude: 12.8333,
    currency: {
      unicode: "🇮🇹",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Jamaica",
    capital: "Kingston",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg",
    iso2: "JM",
    iso3: "JAM",
    dail_code: "+1876",
    latitude: 18.25,
    longitude: -77.5,
    currency: {
      unicode: "🇯🇲",
      code: "JMD",
      name: "Jamaican Dollar",
      symbol: "J$",
    },
  },
  {
    name: "Japan",
    capital: "Tokyo",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg",
    iso2: "JP",
    iso3: "JPN",
    dail_code: "+81",
    latitude: 36,
    longitude: 138,
    currency: {
      unicode: "🇯🇵",
      code: "JPY",
      name: "Japanese Yen",
      symbol: "¥",
    },
  },
  {
    name: "Jersey",
    capital: "Saint Helier",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Flag_of_Jersey.svg",
    iso2: "JE",
    iso3: "JEY",
    dail_code: "+44",
    latitude: 49.21,
    longitude: -2.13,
    currency: {
      unicode: "🇯🇪",
      code: "GBP",
      name: "British Pound Sterling",
      symbol: "£",
    },
  },
  {
    name: "Jordan",
    capital: "Amman",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg",
    iso2: "JO",
    iso3: "JOR",
    dail_code: "+962",
    latitude: 31,
    longitude: 36,
    currency: {
      unicode: "🇯🇴",
      code: "JOD",
      name: "Jordanian Dinar",
      symbol: "ا.د",
    },
  },
  {
    name: "Kazakhstan",
    capital: "Astana",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg",
    iso2: "KZ",
    iso3: "KAZ",
    dail_code: "+7",
    latitude: 48,
    longitude: 68,
    currency: {
      unicode: "🇰🇿",
      code: "KZT",
      name: "Kazakhstani Tenge",
      symbol: "лв",
    },
  },
  {
    name: "Kenya",
    capital: "Nairobi",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg",
    iso2: "KE",
    iso3: "KEN",
    dail_code: "+254",
    latitude: 1,
    longitude: 38,
    currency: {
      unicode: "🇰🇪",
      code: "KES",
      name: "Kenyan Shilling",
      symbol: "KSh",
    },
  },
  {
    name: "Kiribati",
    capital: "Tarawa",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kiribati.svg",
    iso2: "KI",
    iso3: "KIR",
    dail_code: "+686",
    latitude: 1.4167,
    longitude: 173,
    currency: {
      unicode: "🇰🇮",
      code: "AUD",
      name: "Australian Dollar",
      symbol: "$",
    },
  },
  {
    name: "Kuwait",
    capital: "Kuwait City",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg",
    iso2: "KW",
    iso3: "KWT",
    dail_code: "+965",
    latitude: 29.3375,
    longitude: 47.6581,
    currency: {
      unicode: "🇰🇼",
      code: "KWD",
      name: "Kuwaiti Dinar",
      symbol: "ك.د",
    },
  },
  {
    name: "Kyrgyzstan",
    capital: "Bishkek",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg",
    iso2: "KG",
    iso3: "KGZ",
    dail_code: "+996",
    latitude: 41,
    longitude: 75,
    currency: {
      unicode: "🇰🇬",
      code: "KGS",
      name: "Kyrgystani Som",
      symbol: "лв",
    },
  },
  {
    name: "Lao People's Democratic Republic",
    capital: "Vientiane",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg",
    iso2: "LA",
    iso3: "LAO",
    dail_code: "+856",
    latitude: 18,
    longitude: 105,
    currency: {
      unicode: "🇱🇦",
      code: "LAK",
      name: "Laotian Kip",
      symbol: "₭",
    },
  },
  {
    name: "Latvia",
    capital: "Riga",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg",
    iso2: "LV",
    iso3: "LVA",
    dail_code: "+371",
    latitude: 57,
    longitude: 25,
    currency: {
      unicode: "🇱🇻",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Lebanon",
    capital: "Beirut",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg",
    iso2: "LB",
    iso3: "LBN",
    dail_code: "+961",
    latitude: 33.8333,
    longitude: 35.8333,
    currency: {
      unicode: "🇱🇧",
      code: "LBP",
      name: "Lebanese Pound",
      symbol: "£",
    },
  },
  {
    name: "Lesotho",
    capital: "Maseru",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg",
    iso2: "LS",
    iso3: "LSO",
    dail_code: "+266",
    latitude: -29.5,
    longitude: 28.5,
    currency: {
      unicode: "🇱🇸",
      code: "LSL",
      name: "Lesotho Loti",
      symbol: "L",
    },
  },
  {
    name: "Liberia",
    capital: "Monrovia",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg",
    iso2: "LR",
    iso3: "LBR",
    dail_code: "+231",
    latitude: 6.5,
    longitude: -9.5,
    currency: {
      unicode: "🇱🇷",
      code: "LRD",
      name: "Liberian Dollar",
      symbol: "$",
    },
  },
  {
    name: "Liechtenstein",
    capital: "Vaduz",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Liechtenstein.svg",
    iso2: "LI",
    iso3: "LIE",
    dail_code: "+423",
    latitude: 47.1667,
    longitude: 9.5333,
    currency: {
      unicode: "🇱🇮",
      code: "CHF",
      name: "Swiss Franc",
      symbol: "CHf",
    },
  },
  {
    name: "Lithuania",
    capital: "Vilnius",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg",
    iso2: "LT",
    iso3: "LTU",
    dail_code: "+370",
    latitude: 56,
    longitude: 24,
    currency: {
      unicode: "🇱🇹",
      code: "LTL",
      name: "Lithuanian Litas",
      symbol: "Lt",
    },
  },
  {
    name: "Luxembourg",
    capital: "Luxembourg",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg",
    iso2: "LU",
    iso3: "LUX",
    dail_code: "+352",
    latitude: 49.75,
    longitude: 6.1667,
    currency: {
      unicode: "🇱🇺",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Macao",
    capital: "Macao",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/63/Flag_of_Macau.svg",
    iso2: "MO",
    iso3: "MAC",
    dail_code: "+853",
    latitude: 22.1667,
    longitude: 113.55,
    currency: {
      unicode: "🇲🇴",
      code: "MOP",
      name: "Macanese Pataca",
      symbol: "$",
    },
  },
  {
    name: "Madagascar",
    capital: "Antananarivo",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg",
    iso2: "MG",
    iso3: "MDG",
    dail_code: "+261",
    latitude: -20,
    longitude: 47,
    currency: {
      unicode: "🇲🇬",
      code: "MGA",
      name: "Malagasy Ariary",
      symbol: "Ar",
    },
  },
  {
    name: "Malawi",
    capital: "Lilongwe",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg",
    iso2: "MW",
    iso3: "MWI",
    dail_code: "+265",
    latitude: -13.5,
    longitude: 34,
    currency: {
      unicode: "🇲🇼",
      code: "MWK",
      name: "Malawian Kwacha",
      symbol: "MK",
    },
  },
  {
    name: "Malaysia",
    capital: "Kuala Lumpur",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg",
    iso2: "MY",
    iso3: "MYS",
    dail_code: "+60",
    latitude: 2.5,
    longitude: 112.5,
    currency: {
      unicode: "🇲🇾",
      code: "MYR",
      name: "Malaysian Ringgit",
      symbol: "RM",
    },
  },
  {
    name: "Maldives",
    capital: "Male",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg",
    iso2: "MV",
    iso3: "MDV",
    dail_code: "+960",
    latitude: 3.25,
    longitude: 73,
    currency: {
      unicode: "🇲🇻",
      code: "MVR",
      name: "Maldivian Rufiyaa",
      symbol: "Rf",
    },
  },
  {
    name: "Mali",
    capital: "Bamako",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg",
    iso2: "ML",
    iso3: "MLI",
    dail_code: "+223",
    latitude: 17,
    longitude: -4,
    currency: {
      unicode: "🇲🇱",
      code: "XOF",
      name: "CFA Franc BCEAO",
      symbol: "CFA",
    },
  },
  {
    name: "Malta",
    capital: "Valletta",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg",
    iso2: "MT",
    iso3: "MLT",
    dail_code: "+356",
    latitude: 35.8333,
    longitude: 14.5833,
    currency: {
      unicode: "🇲🇹",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Marshall Islands",
    capital: "Majuro",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg",
    iso2: "MH",
    iso3: "MHL",
    dail_code: "+692",
    latitude: 9,
    longitude: 168,
    currency: {
      unicode: "🇲🇭",
      code: "USD",
      name: "US Dollar",
      symbol: "$",
    },
  },
  {
    name: "Martinique",
    capital: "Fort-de-France",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Unofficial_flag_of_Guadeloupe_%28local%29.svg",
    iso2: "MQ",
    iso3: "MTQ",
    dail_code: "+596",
    latitude: 14.6667,
    longitude: -61,
    currency: {
      unicode: "🇲🇶",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Mauritania",
    capital: "Nouakchott",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg",
    iso2: "MR",
    iso3: "MRT",
    dail_code: "+222",
    latitude: 20,
    longitude: -12,
    currency: {
      unicode: "🇲🇷",
      code: "MRO",
      name: "Mauritanian Ouguiya",
      symbol: "MRU",
    },
  },
  {
    name: "Mauritius",
    capital: "Port Louis",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg",
    iso2: "MU",
    iso3: "MUS",
    dail_code: "+230",
    latitude: -20.2833,
    longitude: 57.55,
    currency: {
      unicode: "🇲🇺",
      code: "MUR",
      name: "Mauritian Rupee",
      symbol: "₨",
    },
  },
  {
    name: "Mayotte",
    capital: "Mamoudzou",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg",
    iso2: "YT",
    iso3: "MYT",
    dail_code: "+262",
    latitude: -12.8333,
    longitude: 45.1667,
    currency: {
      unicode: "🇾🇹",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Mexico",
    capital: "Mexico City",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg",
    iso2: "MX",
    iso3: "MEX",
    dail_code: "+52",
    latitude: 23,
    longitude: -102,
    currency: {
      unicode: "🇲🇽",
      code: "MXN",
      name: "Mexican Peso",
      symbol: "$",
    },
  },
  {
    name: "Monaco",
    capital: "Monaco",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg",
    iso2: "MC",
    iso3: "MCO",
    dail_code: "+377",
    latitude: 43.7333,
    longitude: 7.4,
    currency: {
      unicode: "🇲🇨",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Mongolia",
    capital: "Ulan Bator",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg",
    iso2: "MN",
    iso3: "MNG",
    dail_code: "+976",
    latitude: 46,
    longitude: 105,
    currency: {
      unicode: "🇲🇳",
      code: "MNT",
      name: "Mongolian Tugrik",
      symbol: "₮",
    },
  },
  {
    name: "Montenegro",
    capital: "Podgorica",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg",
    iso2: "ME",
    iso3: "MNE",
    dail_code: "+382",
    latitude: 42,
    longitude: 19,
    currency: {
      unicode: "🇲🇪",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Montserrat",
    capital: "Plymouth",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Montserrat.svg",
    iso2: "MS",
    iso3: "MSR",
    dail_code: "+1664",
    latitude: 16.75,
    longitude: -62.2,
    currency: {
      unicode: "🇲🇸",
      code: "XCD",
      name: "East Caribbean Dollar",
      symbol: "$",
    },
  },
  {
    name: "Morocco",
    capital: "Rabat",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg",
    iso2: "MA",
    iso3: "MAR",
    dail_code: "+212",
    latitude: 32,
    longitude: -5,
    currency: {
      unicode: "🇲🇦",
      code: "MAD",
      name: "Moroccan Dirham",
      symbol: "MAD",
    },
  },
  {
    name: "Mozambique",
    capital: "Maputo",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg",
    iso2: "MZ",
    iso3: "MOZ",
    dail_code: "+258",
    latitude: -18.25,
    longitude: 35,
    currency: {
      unicode: "🇲🇿",
      code: "MZM",
      name: "Mozambican Metical",
      symbol: "MT",
    },
  },
  {
    name: "Myanmar",
    capital: "Nay Pyi Taw",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg",
    iso2: "MM",
    iso3: "MMR",
    dail_code: "+95",
    latitude: 22,
    longitude: 98,
    currency: {
      unicode: "🇲🇲",
      code: "MMK",
      name: "Myanmar Kyat",
      symbol: "K",
    },
  },
  {
    name: "Namibia",
    capital: "Windhoek",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg",
    iso2: "NA",
    iso3: "NAM",
    dail_code: "+264",
    latitude: -22,
    longitude: 17,
    currency: {
      unicode: "🇳🇦",
      code: "NAD",
      name: "Namibian Dollar",
      symbol: "$",
    },
  },
  {
    name: "Nauru",
    capital: "Yaren",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/30/Flag_of_Nauru.svg",
    iso2: "NR",
    iso3: "NRU",
    dail_code: "+674",
    latitude: -0.5333,
    longitude: 166.9167,
    currency: {
      unicode: "🇳🇷",
      code: "AUD",
      name: "Australian Dollar",
      symbol: "$",
    },
  },
  {
    name: "Nepal",
    capital: "Kathmandu",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg",
    iso2: "NP",
    iso3: "NPL",
    dail_code: "+977",
    latitude: 28,
    longitude: 84,
    currency: {
      unicode: "🇳🇵",
      code: "NPR",
      name: "Nepalese Rupee",
      symbol: "₨",
    },
  },
  {
    name: "Netherlands",
    capital: "Amsterdam",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg",
    iso2: "NL",
    iso3: "NLD",
    dail_code: "+31",
    latitude: 52.5,
    longitude: 5.75,
    currency: {
      unicode: "🇳🇱",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "New Caledonia",
    capital: "Noumea",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/26/Flags_of_New_Caledonia.svg",
    iso2: "NC",
    iso3: "NCL",
    dail_code: "+687",
    latitude: -21.5,
    longitude: 165.5,
    currency: {
      unicode: "🇳🇨",
      code: "XPF",
      name: "CFP Franc",
      symbol: "₣",
    },
  },
  {
    name: "New Zealand",
    capital: "Wellington",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg",
    iso2: "NZ",
    iso3: "NZL",
    dail_code: "+64",
    latitude: -41,
    longitude: 174,
    currency: {
      unicode: "🇳🇿",
      code: "NZD",
      name: "New Zealand Dollar",
      symbol: "$",
    },
  },
  {
    name: "Nicaragua",
    capital: "Managua",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Nicaragua.svg",
    iso2: "NI",
    iso3: "NIC",
    dail_code: "+505",
    latitude: 13,
    longitude: -85,
    currency: {
      unicode: "🇳🇮",
      code: "NIO",
      name: "Nicaraguan CÃ³rdoba",
      symbol: "C$",
    },
  },
  {
    name: "Niger",
    capital: "Niamey",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg",
    iso2: "NE",
    iso3: "NER",
    dail_code: "+227",
    latitude: 16,
    longitude: 8,
    currency: {
      unicode: "🇳🇪",
      code: "XOF",
      name: "CFA Franc BCEAO",
      symbol: "CFA",
    },
  },
  {
    name: "Nigeria",
    capital: "Abuja",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg",
    iso2: "NG",
    iso3: "NGA",
    dail_code: "+234",
    latitude: 10,
    longitude: 8,
    currency: {
      unicode: "🇳🇬",
      code: "NGN",
      name: "Nigerian Naira",
      symbol: "₦",
    },
  },
  {
    name: "Niue",
    capital: "Alofi",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Niue.svg",
    iso2: "NU",
    iso3: "NIU",
    dail_code: "+683",
    latitude: -19.0333,
    longitude: -169.8667,
    currency: {
      unicode: "🇳🇺",
      code: "NZD",
      name: "New Zealand Dollar",
      symbol: "$",
    },
  },
  {
    name: "Norfolk Island",
    capital: "Kingston",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Norfolk_Island.svg",
    iso2: "NF",
    iso3: "NFK",
    dail_code: "+672",
    latitude: -29.0333,
    longitude: 167.95,
    currency: {
      unicode: "🇳🇫",
      code: "AUD",
      name: "Australian Dollar",
      symbol: "$",
    },
  },
  {
    name: "North Korea",
    capital: "Pyongyang",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/51/Flag_of_North_Korea.svg",
    iso2: "KP",
    iso3: "PRK",
    dail_code: "+850",
    latitude: 40.3399,
    longitude: 127.5101,
    currency: {
      unicode: "🇰🇵",
      code: "KPW",
      name: "North Korean Won",
      symbol: "₩",
    },
  },
  {
    name: "Northern Mariana Islands",
    capital: "Saipan",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Flag_of_the_Northern_Mariana_Islands.svg",
    iso2: "MP",
    iso3: "MNP",
    dail_code: "+1670",
    latitude: 15.2,
    longitude: 145.75,
    currency: {
      unicode: "🇲🇵",
      code: "USD",
      name: "US Dollar",
      symbol: "$",
    },
  },
  {
    name: "Norway",
    capital: "Oslo",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg",
    iso2: "NO",
    iso3: "NOR",
    dail_code: "+47",
    latitude: 62,
    longitude: 10,
    currency: {
      unicode: "🇳🇴",
      code: "NOK",
      name: "Norwegian Krone",
      symbol: "kr",
    },
  },
  {
    name: "Oman",
    capital: "Muscat",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg",
    iso2: "OM",
    iso3: "OMN",
    dail_code: "+968",
    latitude: 21,
    longitude: 57,
    currency: {
      unicode: "🇴🇲",
      code: "OMR",
      name: "Omani Rial",
      symbol: ".ع.ر",
    },
  },
  {
    name: "Pakistan",
    capital: "Islamabad",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg",
    iso2: "PK",
    iso3: "PAK",
    dail_code: "+92",
    latitude: 30,
    longitude: 70,
    currency: {
      unicode: "🇵🇰",
      code: "PKR",
      name: "Pakistani Rupee",
      symbol: "₨",
    },
  },
  {
    name: "Palau",
    capital: "Melekeok",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Palau.svg",
    iso2: "PW",
    iso3: "PLW",
    dail_code: "+680",
    latitude: 7.5,
    longitude: 134.5,
    currency: {
      unicode: "🇵🇼",
      code: "USD",
      name: "US Dollar",
      symbol: "$",
    },
  },
  {
    name: "Panama",
    capital: "Panama City",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg",
    iso2: "PA",
    iso3: "PAN",
    dail_code: "+507",
    latitude: 9,
    longitude: -80,
    currency: {
      unicode: "🇵🇦",
      code: "PAB",
      name: "Panamanian Balboa",
      symbol: "B/.",
    },
  },
  {
    name: "Papua New Guinea",
    capital: "Port Moresby",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg",
    iso2: "PG",
    iso3: "PNG",
    dail_code: "+675",
    latitude: -6,
    longitude: 147,
    currency: {
      unicode: "🇵🇬",
      code: "PGK",
      name: "Papua New Guinean Kina",
      symbol: "K",
    },
  },
  {
    name: "Paraguay",
    capital: "Asuncion",
    continent: "SA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg",
    iso2: "PY",
    iso3: "PRY",
    dail_code: "+595",
    latitude: -23,
    longitude: -58,
    currency: {
      unicode: "🇵🇾",
      code: "PYG",
      name: "Paraguayan Guarani",
      symbol: "₲",
    },
  },
  {
    name: "Peru",
    capital: "Lima",
    continent: "SA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg",
    iso2: "PE",
    iso3: "PER",
    dail_code: "+51",
    latitude: -10,
    longitude: -76,
    currency: {
      unicode: "🇵🇪",
      code: "PEN",
      name: "Peruvian Nuevo Sol",
      symbol: "S/.",
    },
  },
  {
    name: "Philippines",
    capital: "Manila",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg",
    iso2: "PH",
    iso3: "PHL",
    dail_code: "+63",
    latitude: 13,
    longitude: 122,
    currency: {
      unicode: "🇵🇭",
      code: "PHP",
      name: "Philippine Peso",
      symbol: "₱",
    },
  },
  {
    name: "Pitcairn",
    capital: "Adamstown",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_the_Pitcairn_Islands.svg",
    iso2: "PN",
    iso3: "PCN",
    dail_code: "+870",
    latitude: -24.7,
    longitude: -127.4,
    currency: {
      unicode: "🇵🇳",
      code: "NZD",
      name: "New Zealand Dollar",
      symbol: "$",
    },
  },
  {
    name: "Poland",
    capital: "Warsaw",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg",
    iso2: "PL",
    iso3: "POL",
    dail_code: "+48",
    latitude: 52,
    longitude: 20,
    currency: {
      unicode: "🇵🇱",
      code: "PLN",
      name: "Polish Zloty",
      symbol: "zł",
    },
  },
  {
    name: "Portugal",
    capital: "Lisbon",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg",
    iso2: "PT",
    iso3: "PRT",
    dail_code: "+351",
    latitude: 39.5,
    longitude: -8,
    currency: {
      unicode: "🇵🇹",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Puerto Rico",
    capital: "San Juan",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Puerto_Rico.svg",
    iso2: "PR",
    iso3: "PRI",
    dail_code: "+1939",
    latitude: 18.25,
    longitude: -66.5,
    currency: {
      unicode: "🇵🇷",
      code: "USD",
      name: "US Dollar",
      symbol: "$",
    },
  },
  {
    name: "Qatar",
    capital: "Doha",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg",
    iso2: "QA",
    iso3: "QAT",
    dail_code: "+974",
    latitude: 25.5,
    longitude: 51.25,
    currency: {
      unicode: "🇶🇦",
      code: "QAR",
      name: "Qatari Rial",
      symbol: "ق.ر",
    },
  },
  {
    name: "Romania",
    capital: "Bucharest",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg",
    iso2: "RO",
    iso3: "ROU",
    dail_code: "+40",
    latitude: 46,
    longitude: 25,
    currency: {
      unicode: "🇷🇴",
      code: "RON",
      name: "Romanian Leu",
      symbol: "lei",
    },
  },
  {
    name: "Russia",
    capital: "Moscow",
    continent: "AS/EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Russia.svg",
    iso2: "RU",
    iso3: "RUS",
    dail_code: "+7",
    latitude: 61.524,
    longitude: 105.3188,
    currency: {
      unicode: "🇷🇺",
      code: "RUB",
      name: "Russian Ruble",
      symbol: "₽",
    },
  },
  {
    name: "Rwanda",
    capital: "Kigali",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg",
    iso2: "RW",
    iso3: "RWA",
    dail_code: "+250",
    latitude: -2,
    longitude: 30,
    currency: {
      unicode: "🇷🇼",
      code: "RWF",
      name: "Rwandan Franc",
      symbol: "FRw",
    },
  },
  {
    name: "Réunion",
    capital: "Saint-Denis",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg",
    iso2: "RE",
    iso3: "REU",
    dail_code: "+262",
    latitude: -21.1,
    longitude: 55.6,
    currency: {
      unicode: "🇷🇪",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },

  {
    name: "Saint Kitts and Nevis",
    capital: "Basseterre",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg",
    iso2: "KN",
    iso3: "KNA",
    dail_code: "+1869",
    latitude: 17.3333,
    longitude: -62.75,
    currency: {
      unicode: "🇰🇳",
      code: "XCD",
      name: "East Caribbean Dollar",
      symbol: "$",
    },
  },
  {
    name: "Saint Lucia",
    capital: "Castries",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg",
    iso2: "LC",
    iso3: "LCA",
    dail_code: "+1758",
    latitude: 13.8833,
    longitude: -61.1333,
    currency: {
      unicode: "🇱🇨",
      code: "XCD",
      name: "East Caribbean Dollar",
      symbol: "$",
    },
  },
  {
    name: "Saint Pierre and Miquelon",
    capital: "Saint-Pierre",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_Saint-Pierre_and_Miquelon.svg",
    iso2: "PM",
    iso3: "SPM",
    dail_code: "+508",
    latitude: 46.8333,
    longitude: -56.3333,
    currency: {
      unicode: "🇵🇲",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg",
    iso2: "VC",
    iso3: "VCT",
    dail_code: "+1784",
    latitude: 13.25,
    longitude: -61.2,
    currency: {
      unicode: "🇻🇨",
      code: "XCD",
      name: "East Caribbean Dollar",
      symbol: "$",
    },
  },
  {
    name: "Samoa",
    capital: "Apia",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Samoa.svg",
    iso2: "WS",
    iso3: "WSM",
    dail_code: "+685",
    latitude: -13.5833,
    longitude: -172.3333,
    currency: {
      unicode: "🇼🇸",
      code: "WST",
      name: "Samoan Tala",
      symbol: "SAT",
    },
  },
  {
    name: "San Marino",
    capital: "San Marino",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg",
    iso2: "SM",
    iso3: "SMR",
    dail_code: "+378",
    latitude: 43.7667,
    longitude: 12.4167,
    currency: {
      unicode: "🇸🇲",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Sao Tome and Principe",
    capital: "Sao Tome",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Sao_Tome_and_Principe.svg",
    iso2: "ST",
    iso3: "STP",
    dail_code: "+239",
    latitude: 1,
    longitude: 7,
    currency: {
      unicode: "🇸🇹",
      code: "STD",
      name: "São Tomé and Príncipe Dobra",
      symbol: "Db",
    },
  },
  {
    name: "Saudi Arabia",
    capital: "Riyadh",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg",
    iso2: "SA",
    iso3: "SAU",
    dail_code: "+966",
    latitude: 25,
    longitude: 45,
    currency: {
      unicode: "🇸🇦",
      code: "SAR",
      name: "Saudi Riyal",
      symbol: "﷼",
    },
  },
  {
    name: "Senegal",
    capital: "Dakar",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg",
    iso2: "SN",
    iso3: "SEN",
    dail_code: "+221",
    latitude: 14,
    longitude: -14,
    currency: {
      unicode: "🇸🇳",
      code: "XOF",
      name: "CFA Franc BCEAO",
      symbol: "CFA",
    },
  },
  {
    name: "Serbia",
    capital: "Belgrade",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg",
    iso2: "RS",
    iso3: "SRB",
    dail_code: "+381",
    latitude: 44,
    longitude: 21,
    currency: {
      unicode: "🇷🇸",
      code: "RSD",
      name: "Serbian Dinar",
      symbol: "din",
    },
  },
  {
    name: "Seychelles",
    capital: "Victoria",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Seychelles.svg",
    iso2: "SC",
    iso3: "SYC",
    dail_code: "+248",
    latitude: -4.5833,
    longitude: 55.6667,
    currency: {
      unicode: "🇸🇨",
      code: "SCR",
      name: "Seychellois Rupee",
      symbol: "SRe",
    },
  },
  {
    name: "Sierra Leone",
    capital: "Freetown",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg",
    iso2: "SL",
    iso3: "SLE",
    dail_code: "+232",
    latitude: 8.5,
    longitude: -11.5,
    currency: {
      unicode: "🇸🇱",
      code: "SLL",
      name: "Sierra Leonean Leone",
      symbol: "Le",
    },
  },
  {
    name: "Singapore",
    capital: "Singapur",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg",
    iso2: "SG",
    iso3: "SGP",
    dail_code: "+65",
    latitude: 1.3667,
    longitude: 103.8,
    currency: {
      unicode: "🇸🇬",
      code: "SGD",
      name: "Singapore Dollar",
      symbol: "$",
    },
  },
  {
    name: "Slovakia",
    capital: "Bratislava",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg",
    iso2: "SK",
    iso3: "SVK",
    dail_code: "+421",
    latitude: 48.6667,
    longitude: 19.5,
    currency: {
      unicode: "🇸🇰",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Slovenia",
    capital: "Ljubljana",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg",
    iso2: "SI",
    iso3: "SVN",
    dail_code: "+386",
    latitude: 46,
    longitude: 15,
    currency: {
      unicode: "🇸🇮",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Solomon Islands",
    capital: "Honiara",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg",
    iso2: "SB",
    iso3: "SLB",
    dail_code: "+677",
    latitude: -8,
    longitude: 159,
    currency: {
      unicode: "🇸🇧",
      code: "SBD",
      name: "Solomon Islands Dollar",
      symbol: "Si$",
    },
  },
  {
    name: "Somalia",
    capital: "Mogadishu",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg",
    iso2: "SO",
    iso3: "SOM",
    dail_code: "+252",
    latitude: 10,
    longitude: 49,
    currency: {
      unicode: "🇸🇴",
      code: "SOS",
      name: "Somali Shilling",
      symbol: "Sh.so.",
    },
  },
  {
    name: "South Africa",
    capital: "Pretoria",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg",
    iso2: "ZA",
    iso3: "ZAF",
    dail_code: "+27",
    latitude: -29,
    longitude: 24,
    currency: {
      unicode: "🇿🇦",
      code: "ZAR",
      name: "South African Rand",
      symbol: "R",
    },
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    capital: "Grytviken",
    continent: "AN",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg",
    iso2: "GS",
    iso3: "SGS",
    dail_code: "+500",
    latitude: -54.5,
    longitude: -37,
    currency: {
      unicode: "🇬🇸",
      code: "GBP",
      name: "British Pound Sterling",
      symbol: "£",
    },
  },
  {
    name: "South Korea",
    capital: "Seoul",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg",
    iso2: "KR",
    iso3: "KOR",
    dail_code: "+82",
    latitude: 35.9078,
    longitude: 127.7669,
    currency: {
      unicode: "🇰🇷",
      name: "South Korean Won",
      code: "KRW",
      symbol: "₩",
    },
  },
  {
    name: "Spain",
    capital: "Madrid",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg",
    iso2: "ES",
    iso3: "ESP",
    dail_code: "+34",
    latitude: 40,
    longitude: -4,
    currency: {
      unicode: "🇪🇸",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Sri Lanka",
    capital: "Colombo",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg",
    iso2: "LK",
    iso3: "LKA",
    dail_code: "+94",
    latitude: 7,
    longitude: 81,
    currency: {
      unicode: "🇱🇰",
      code: "LKR",
      name: "Sri Lankan Rupee",
      symbol: "Rs",
    },
  },
  {
    name: "Sudan",
    capital: "Khartoum",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg",
    iso2: "SD",
    iso3: "SDN",
    dail_code: "+249",
    latitude: 15,
    longitude: 30,
    currency: {
      unicode: "🇸🇩",
      code: "SDG",
      name: "Sudanese Pound",
      symbol: ".س.ج",
    },
  },
  {
    name: "Suriname",
    capital: "Paramaribo",
    continent: "SA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Suriname.svg",
    iso2: "SR",
    iso3: "SUR",
    dail_code: "+597",
    latitude: 4,
    longitude: -56,
    currency: {
      unicode: "🇸🇷",
      code: "SRD",
      name: "Surinamese Dollar",
      symbol: "$",
    },
  },
  {
    name: "Sweden",
    capital: "Stockholm",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg",
    iso2: "SE",
    iso3: "SWE",
    dail_code: "+46",
    latitude: 62,
    longitude: 15,
    currency: {
      unicode: "🇸🇪",
      code: "SEK",
      name: "Swedish Krona",
      symbol: "kr",
    },
  },
  {
    name: "Switzerland",
    capital: "Berne",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Switzerland_%28Pantone%29.svg",
    iso2: "CH",
    iso3: "CHE",
    dail_code: "+41",
    latitude: 47,
    longitude: 8,
    currency: {
      unicode: "🇨🇭",
      code: "CHF",
      name: "Swiss Franc",
      symbol: "CHf",
    },
  },
  {
    name: "Syrian Arab Republic",
    capital: "Damascus",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Syria.svg",
    iso2: "SY",
    iso3: "SYR",
    dail_code: "+963",
    latitude: 35,
    longitude: 38,
    currency: {
      unicode: "🇸🇾",
      code: "SYP",
      name: "Syrian Pound",
      symbol: "LS",
    },
  },
  {
    name: "Taiwan",
    capital: "Taipei",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg",
    iso2: "TW",
    iso3: "TWN",
    dail_code: "+886",
    latitude: 23.5,
    longitude: 121,
    currency: {
      unicode: "🇹🇼",
      code: "TWD",
      name: "New Taiwan Dollar",
      symbol: "$",
    },
  },
  {
    name: "Tajikistan",
    capital: "Dushanbe",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg",
    iso2: "TJ",
    iso3: "TJK",
    dail_code: "+992",
    latitude: 39,
    longitude: 71,
    currency: {
      unicode: "🇹🇯",
      code: "TJS",
      name: "Tajikistani Somoni",
      symbol: "SM",
    },
  },
  {
    name: "Thailand",
    capital: "Bangkok",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg",
    iso2: "TH",
    iso3: "THA",
    dail_code: "+66",
    latitude: 15,
    longitude: 100,
    currency: {
      unicode: "🇹🇭",
      code: "THB",
      name: "Thai Baht",
      symbol: "฿",
    },
  },
  {
    name: "Togo",
    capital: "Lome",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg",
    iso2: "TG",
    iso3: "TGO",
    dail_code: "+228",
    latitude: 8,
    longitude: 1.1667,
    currency: {
      unicode: "🇹🇬",
      code: "XOF",
      name: "CFA Franc BCEAO",
      symbol: "CFA",
    },
  },
  {
    name: "Tokelau",
    capital: "",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Flag_of_Tokelau.svg",
    iso2: "TK",
    iso3: "TKL",
    dail_code: "+690",
    latitude: -9,
    longitude: -172,
    currency: {
      unicode: "🇹🇰",
      code: "NZD",
      name: "New Zealand Dollar",
      symbol: "$",
    },
  },
  {
    name: "Tonga",
    capital: "Nuku'alofa",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg",
    iso2: "TO",
    iso3: "TON",
    dail_code: "+676",
    latitude: -20,
    longitude: -175,
    currency: {
      unicode: "🇹🇴",
      code: "TOP",
      name: "Tongan Pa'anga",
      symbol: "$",
    },
  },
  {
    name: "Trinidad and Tobago",
    capital: "Port of Spain",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg",
    iso2: "TT",
    iso3: "TTO",
    dail_code: "+1868",
    latitude: 11,
    longitude: -61,
    currency: {
      unicode: "🇹🇹",
      code: "TTD",
      name: "Trinidad & Tobago Dollar",
      symbol: "$",
    },
  },
  {
    name: "Tunisia",
    capital: "Tunis",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg",
    iso2: "TN",
    iso3: "TUN",
    dail_code: "+216",
    latitude: 34,
    longitude: 9,
    currency: {
      unicode: "🇹🇳",
      code: "TND",
      name: "Tunisian Dinar",
      symbol: "ت.د",
    },
  },
  {
    name: "Turkey",
    capital: "Ankara",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
    iso2: "TR",
    iso3: "TUR",
    dail_code: "+90",
    latitude: 39,
    longitude: 35,
    currency: {
      unicode: "🇹🇷",
      code: "TRY",
      name: "Turkish Lira",
      symbol: "₺",
    },
  },
  {
    name: "Turkmenistan",
    capital: "Ashgabat",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg",
    iso2: "TM",
    iso3: "TKM",
    dail_code: "+993",
    latitude: 40,
    longitude: 60,
    currency: {
      unicode: "🇹🇲",
      code: "TMT",
      name: "Turkmenistani Manat",
      symbol: "T",
    },
  },
  {
    name: "Turks and Caicos Islands",
    capital: "Cockburn Town",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg",
    iso2: "TC",
    iso3: "TCA",
    dail_code: "+1649",
    latitude: 21.75,
    longitude: -71.5833,
    currency: {
      unicode: "🇹🇨",
      code: "USD",
      name: "US Dollar",
      symbol: "$",
    },
  },
  {
    name: "Tuvalu",
    capital: "Funafuti",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg",
    iso2: "TV",
    iso3: "TUV",
    dail_code: "+688",
    latitude: -8,
    longitude: 178,
    currency: {
      unicode: "🇹🇻",
      code: "AUD",
      name: "Australian Dollar",
      symbol: "$",
    },
  },
  {
    name: "Uganda",
    capital: "Kampala",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg",
    iso2: "UG",
    iso3: "UGA",
    dail_code: "+256",
    latitude: 1,
    longitude: 32,
    currency: {
      unicode: "🇺🇬",
      code: "UGX",
      name: "Ugandan Shilling",
      symbol: "USh",
    },
  },
  {
    name: "Ukraine",
    capital: "Kiev",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg",
    iso2: "UA",
    iso3: "UKR",
    dail_code: "+380",
    latitude: 49,
    longitude: 32,
    currency: {
      unicode: "🇺🇦",
      code: "UAH",
      name: "Ukrainian Hryvnia",
      symbol: "₴",
    },
  },
  {
    name: "United Arab Emirates",
    capital: "Abu Dhabi",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg",
    iso2: "AE",
    iso3: "ARE",
    dail_code: "+971",
    latitude: 24,
    longitude: 54,
    currency: {
      unicode: "🇦🇪",
      code: "AED",
      name: "United Arab Emirates Dirham",
      symbol: "إ.د",
    },
  },
  {
    name: "United Kingdom",
    capital: "London",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg",
    iso2: "GB",
    iso3: "GBR",
    dail_code: "+44",
    latitude: 54,
    longitude: -2,
    currency: {
      unicode: "🇬🇧",
      code: "GBP",
      name: "British Pound Sterling",
      symbol: "£",
    },
  },
  {
    name: "United States",
    capital: "Washington",
    continent: "NA",
    flag: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
    iso2: "US",
    iso3: "USA",
    dail_code: "+1",
    latitude: 38,
    longitude: -97,
    currency: {
      unicode: "🇺🇸",
      code: "USD",
      name: "US Dollar",
      symbol: "$",
    },
  },
  {
    name: "United States Minor Outlying Islands",
    capital: "",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
    iso2: "UM",
    iso3: "UMI",
    dail_code: "+1581",
    latitude: 19.2833,
    longitude: 166.6,
    currency: {
      unicode: "🇺🇲",
      code: "USD",
      name: "US Dollar",
      symbol: "$",
    },
  },
  {
    name: "Uruguay",
    capital: "Montevideo",
    continent: "SA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg",
    iso2: "UY",
    iso3: "URY",
    dail_code: "+598",
    latitude: -33,
    longitude: -56,
    currency: {
      unicode: "🇺🇾",
      code: "UYU",
      name: "Uruguayan Peso",
      symbol: "$",
    },
  },
  {
    name: "Uzbekistan",
    capital: "Tashkent",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg",
    iso2: "UZ",
    iso3: "UZB",
    dail_code: "+998",
    latitude: 41,
    longitude: 64,
    currency: {
      unicode: "🇺🇿",
      code: "UZS",
      name: "Uzbekistan Som",
      symbol: "лв",
    },
  },
  {
    name: "Vanuatu",
    capital: "Port Vila",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Vanuatu.svg",
    iso2: "VU",
    iso3: "VUT",
    dail_code: "+678",
    latitude: -16,
    longitude: 167,
    currency: {
      unicode: "🇻🇺",
      code: "VUV",
      name: "Vanuatu Vatu",
      symbol: "VT",
    },
  },
  {
    name: "Vatican City",
    capital: "Vatican City",
    continent: "EU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_the_Vatican_City.svg",
    iso2: "VA",
    iso3: "VAT",
    dail_code: "+379",
    latitude: 41.9,
    longitude: 12.45,
    currency: {
      unicode: "🇻🇦",
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
  },
  {
    name: "Vietnam",
    capital: "Hanoi",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
    iso2: "VN",
    iso3: "VNM",
    dail_code: "+84",
    latitude: 16,
    longitude: 106,
    currency: {
      unicode: "🇻🇳",
      code: "VND",
      name: "Vietnamese Dong",
      symbol: "₫",
    },
  },
  {
    name: "Wallis and Futuna",
    capital: "Mata Utu",
    continent: "OC",
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Flag_of_Wallis_and_Futuna.svg",
    iso2: "WF",
    iso3: "WLF",
    dail_code: "+681",
    latitude: -13.3,
    longitude: -176.2,
    currency: {
      unicode: "🇼🇫",
      code: "XPF",
      name: "CFP Franc",
      symbol: "₣",
    },
  },
  {
    name: "Yemen",
    capital: "Sanaa",
    continent: "AS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg",
    iso2: "YE",
    iso3: "YEM",
    dail_code: "+967",
    latitude: 15,
    longitude: 48,
    currency: {
      unicode: "🇾🇪",
      code: "YER",
      name: "Yemeni Rial",
      symbol: "﷼",
    },
  },
  {
    name: "Zambia",
    capital: "Lusaka",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg",
    iso2: "ZM",
    iso3: "ZMB",
    dail_code: "+260",
    latitude: -15,
    longitude: 30,
    currency: {
      unicode: "🇿🇲",
      code: "ZMK",
      name: "Zambian Kwacha",
      symbol: "ZK",
    },
  },
  {
    name: "Zimbabwe",
    capital: "Harare",
    continent: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg",
    iso2: "ZW",
    iso3: "ZWE",
    dail_code: "+263",
    latitude: -20,
    longitude: 30,
    currency: {
      unicode: "🇿🇼",
      code: "ZWL",
      name: "Zimbabwean Dollar",
      symbol: "Z$",
    },
  },
];

export default countries;
